---
title: "CardiovascBMI"
author: "Flavien Moise"
date: "2024-04-12"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readr)
library(shiny)

data <- read.csv('cardio_train.csv', sep=';')

data$bmi <- data$weight / (data$height / 100)^2

ui <- fluidPage(
  titlePanel("BMI Distribution"),
  sidebarLayout(
    sidebarPanel(
      numericInput("height", "Enter your height (in cm):", value = NULL),
      numericInput("weight", "Enter your weight (in kg):", value = NULL),
      actionButton("submit", "Submit")
    ),
    mainPanel(
      plotOutput("bmi_plot")
    )
  )
)
server <- function(input, output, session) {
  output$bmi_plot <- renderPlot({
    filtered_data <- data[data$bmi <= 60, ]
    
    plot(1, type = "n", xlim = range(filtered_data$bmi), ylim = c(0, 0.15),
         main = "Distribution of BMI", xlab = "BMI", ylab = "Density")
    
    lines(density(filtered_data$bmi[filtered_data$cardio == 1]), col = "blue", lwd = 2)
    lines(density(filtered_data$bmi[filtered_data$cardio == 0]), col = "red", lwd = 2)
    
    legend("topright", legend = c("Cardio 1", "Cardio 0"), col = c("blue", "red"), lwd = 2)
    
    if (!is.null(input$height) && !is.null(input$weight)) {
      data_user <- data.frame(height = input$height, weight = input$weight)
      data_user$bmi <- data_user$weight / (data_user$height / 100)^2
      
      abline(v = data_user$bmi, col = "green", lwd = 2)
    }
  })
}


shinyApp(ui = ui, server = server)

```

